# Generated by Django 4.1.5 on 2023-01-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rename_snippet_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='title',
            new_name='delivery_name',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='font_size',
            new_name='quantity',
        ),
    ]
