# Generated by Django 4.1.5 on 2023-01-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_category_menuitem_ordermodel_delete_delivery'),
        ('customer', '0003_customer_delete_delivery'),
    ]

    operations = [
    ]
